#!/usr/bin/env python3
"""
Memelet Installation Script
Interactive setup for standalone Memelet instances
"""
import os
import sys
import secrets
from pathlib import Path
import subprocess
import platform

def print_header(text):
    """Print a formatted header"""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70 + "\n")

def print_success(text):
    """Print success message"""
    print(f"✓ {text}")

def print_error(text):
    """Print error message"""
    print(f"✗ {text}")

def print_info(text):
    """Print info message"""
    print(f"ℹ {text}")

def get_input(prompt, default=None):
    """Get user input with optional default value"""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    value = input(prompt).strip()
    return value if value else default

def check_python_version():
    """Check if Python version is adequate"""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print_error(f"Python 3.8+ required, found {version.major}.{version.minor}")
        return False
    print_success(f"Python {version.major}.{version.minor}.{version.micro} detected")
    return True

def check_command_exists(command):
    """Check if a command exists in PATH"""
    try:
        subprocess.run([command, "--version"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except FileNotFoundError:
        return False

def generate_secret_key():
    """Generate a secure random secret key"""
    return secrets.token_hex(32)

def setup_cron_job(install_dir):
    """Set up cron job for automatic scanning"""
    cron_command = f"0 * * * * {install_dir}/run_scan.sh"
    
    try:
        # Get current crontab
        result = subprocess.run(
            ['crontab', '-l'],
            capture_output=True,
            text=True
        )
        
        current_crontab = result.stdout if result.returncode == 0 else ""
        
        # Check if already exists
        if 'run_scan.sh' in current_crontab:
            print_info("Cron job already exists, skipping")
            return True
        
        # Add new cron job
        new_crontab = current_crontab.rstrip() + f"\n# Memelet - Automatic hourly scanning\n{cron_command}\n"
        
        # Write back to crontab
        process = subprocess.Popen(
            ['crontab', '-'],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        
        stdout, stderr = process.communicate(input=new_crontab)
        
        if process.returncode == 0:
            print_success("Cron job added successfully")
            print_info(f"Memelet will scan for new memes every hour")
            return True
        else:
            print_error(f"Failed to add cron job: {stderr}")
            return False
            
    except FileNotFoundError:
        print_error("crontab command not found")
        return False
    except Exception as e:
        print_error(f"Failed to set up cron: {e}")
        return False

def create_env_file(config):
    """Create .env file from configuration"""
    env_content = f"""# Memelet Configuration
# Generated by install.py on {config['timestamp']}

# Installation paths
SCRIPT_DIR={config['install_dir']}
MEMES_DIR={config['memes_dir']}
DB_PATH={config['db_path']}
LOG_DIR={config['log_dir']}
VENV_DIR={config['venv_dir']}

# Web server
BASE_URL={config['base_url']}
MEMES_URL_BASE={config['memes_url_base']}
HOST={config['host']}
PORT={config['port']}

# Timezone
TZ={config['timezone']}

# Security
SECRET_KEY={config['secret_key']}

# Disk Quota (optional, in MB)
DISK_QUOTA_MB={config.get('disk_quota_mb', '')}

# API Keys (optional, can also be set in the web UI)
REPLICATE_API_TOKEN={config.get('replicate_token', '')}
"""
    
    env_path = Path(config['install_dir']) / '.env'
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    return env_path

def main():
    """Main installation routine"""
    print_header("Memelet Installation")
    print("This script will help you set up Memelet on your server.\n")
    
    # Check Python version
    if not check_python_version():
        sys.exit(1)
    
    # Get installation directory (current directory)
    install_dir = Path(__file__).parent.resolve()
    print_info(f"Installation directory: {install_dir}")
    
    # Collect configuration
    print("\n--- Configuration ---\n")
    
    config = {
        'timestamp': subprocess.check_output(['date'], text=True).strip(),
        'install_dir': str(install_dir)
    }
    
    # Memes storage directory
    default_memes_dir = str(install_dir / 'files')
    memes_dir = get_input("Memes storage directory", default_memes_dir)
    config['memes_dir'] = memes_dir
    
    # Database path
    default_db_path = str(install_dir / 'memelet.db')
    db_path = get_input("Database file path", default_db_path)
    config['db_path'] = db_path
    
    # Log directory
    default_log_dir = str(install_dir / 'logs')
    log_dir = get_input("Log directory", default_log_dir)
    config['log_dir'] = log_dir
    
    # Virtual environment directory
    default_venv_dir = str(install_dir / 'venv')
    venv_dir = get_input("Virtual environment directory", default_venv_dir)
    config['venv_dir'] = venv_dir
    
    # Base URL
    print("\n--- Web Server Configuration ---\n")
    print_info("This is the public URL where Memelet will be accessible")
    base_url = get_input("Base URL", "http://localhost:5000")
    config['base_url'] = base_url.rstrip('/')
    
    # Memes URL base (auto-calculate from base URL)
    config['memes_url_base'] = f"{config['base_url']}/files/"
    
    # Host
    default_host = "127.0.0.1"
    print_info("Use 0.0.0.0 to accept connections from any IP (use with reverse proxy)")
    host = get_input("Host to bind to", default_host)
    config['host'] = host
    
    # Port
    port = get_input("Port", "5000")
    config['port'] = port
    
    # Timezone
    print("\n--- Regional Settings ---\n")
    print_info("See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones")
    timezone = get_input("Timezone", "UTC")
    config['timezone'] = timezone
    
    # Disk quota
    print("\n--- Disk Quota ---\n")
    print_info("Set a disk space limit for this Memelet instance")
    print_info("Enter quota in MB (e.g., 5000 for 5GB) or leave blank for no limit")
    disk_quota = get_input("Disk quota in MB (optional)", "")
    config['disk_quota_mb'] = disk_quota if disk_quota else ""
    
    # Secret key
    print_info("Generating secure secret key...")
    config['secret_key'] = generate_secret_key()
    print_success("Secret key generated")
    
    # Replicate API token (optional)
    print("\n--- API Configuration ---\n")
    print_info("Replicate API token is optional - you can set it later in the web UI")
    replicate_token = get_input("Replicate API token (optional)", "")
    config['replicate_token'] = replicate_token
    
    # Confirm configuration
    print_header("Configuration Summary")
    print(f"Install directory: {config['install_dir']}")
    print(f"Memes directory:   {config['memes_dir']}")
    print(f"Database path:     {config['db_path']}")
    print(f"Log directory:     {config['log_dir']}")
    print(f"Virtual env:       {config['venv_dir']}")
    print(f"Base URL:          {config['base_url']}")
    print(f"Host:              {config['host']}")
    print(f"Port:              {config['port']}")
    print(f"Timezone:          {config['timezone']}")
    disk_quota_display = f"{config['disk_quota_mb']}MB" if config['disk_quota_mb'] else "No limit"
    print(f"Disk quota:        {disk_quota_display}")
    print()
    
    confirm = get_input("Proceed with installation? (yes/no)", "yes")
    if confirm.lower() not in ['yes', 'y']:
        print("Installation cancelled.")
        sys.exit(0)
    
    # Start installation
    print_header("Installing Memelet")
    
    # Create directories
    print("Creating directories...")
    Path(config['memes_dir']).mkdir(parents=True, exist_ok=True)
    Path(config['memes_dir'], '_albums').mkdir(exist_ok=True)
    Path(config['memes_dir'], '_system', 'temp').mkdir(parents=True, exist_ok=True)
    Path(config['memes_dir'], '_system', 'thumbnails').mkdir(parents=True, exist_ok=True)
    Path(config['log_dir']).mkdir(parents=True, exist_ok=True)
    print_success("Directories created")
    
    # Create .env file
    print("Creating .env file...")
    env_path = create_env_file(config)
    print_success(f".env file created at {env_path}")
    
    # Create virtual environment (optional)
    create_venv = get_input("\nCreate Python virtual environment? (yes/no)", "yes")
    if create_venv.lower() in ['yes', 'y']:
        venv_path = Path(config['venv_dir'])
        if not venv_path.exists():
            print(f"Creating virtual environment at {venv_path}...")
            try:
                subprocess.run([sys.executable, '-m', 'venv', str(venv_path)], check=True)
                print_success("Virtual environment created")
                
                # Install dependencies
                install_deps = get_input("Install Python dependencies? (yes/no)", "yes")
                if install_deps.lower() in ['yes', 'y']:
                    print("Installing dependencies from requirements.txt...")
                    pip_path = venv_path / 'bin' / 'pip' if platform.system() != 'Windows' else venv_path / 'Scripts' / 'pip.exe'
                    subprocess.run([str(pip_path), 'install', '-r', 'requirements.txt'], check=True)
                    print_success("Dependencies installed")
            except Exception as e:
                print_error(f"Failed to create virtual environment: {e}")
        else:
            print_info("Virtual environment already exists")
    
    # Initialize database
    init_db = get_input("\nInitialize database? (yes/no)", "yes")
    if init_db.lower() in ['yes', 'y']:
        print("Initializing database...")
        try:
            # Load env vars for init_database
            with open(env_path) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        os.environ[key] = value
            
            # Run init_database.py
            subprocess.run([sys.executable, 'init_database.py'], check=True)
            print_success("Database initialized")
        except Exception as e:
            print_error(f"Failed to initialize database: {e}")
    
    # Make shell scripts executable
    if platform.system() != 'Windows':
        print("Making shell scripts executable...")
        for script in ['run_scan.sh', 'retry_errors.sh']:
            script_path = install_dir / script
            if script_path.exists():
                script_path.chmod(0o755)
        print_success("Shell scripts are executable")
    
    # Set up automatic scanning with cron (optional)
    if platform.system() != 'Windows':
        print("\n--- Automatic Scanning ---\n")
        setup_cron = get_input("Set up automatic hourly scanning with cron? (yes/no)", "yes")
        
        if setup_cron.lower() in ['yes', 'y']:
            cron_setup_success = setup_cron_job(install_dir)
            if not cron_setup_success:
                print_info("You can set up cron manually later with:")
                print(f"  crontab -e")
                print(f"  # Add this line:")
                print(f"  0 * * * * {install_dir}/run_scan.sh")
    
    # Installation complete
    print_header("Installation Complete!")
    print(f"""
Memelet has been successfully installed!

Next steps:
1. Start Memelet:
   python3 app.py
   (or activate venv first: source {config['venv_dir']}/bin/activate)

2. Access the web interface:
   {config['base_url']}

3. Default login credentials:
   Username: admin
   Password: admin
   (Change this in Settings after first login!)

4. Set up your Replicate API key in Settings if you haven't already

Configuration file: {env_path}
""")
    
    print_info("Enjoy using Memelet! 🎉")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nInstallation cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print_error(f"Installation failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

